name: GitHub Actions

on:
  workflow_dispatch:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:    
  test:
    name: Unit-Tests
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up XCode 
      run: sudo xcode-select --switch /Applications/Xcode_15.1.app

    - name: Bundle Install
      run: bundle install

    - name: Install Cocoapods
      run: bundle exec pod install

    - name: Unit tests
      run: bundle exec fastlane unit_tests
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Code Coverage
      run: bundle exec fastlane coverage

    - name: Lint
      run: bundle exec fastlane lint

    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v8
      
    - name: Send to Sonarcloud
      run: bundle exec fastlane sonarqube
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_KEY }}